version: '3.3'

services:
  voice_restore:
    build: .
    container_name: voice_restore_server
    command: python3 app.py
    volumes:
      - ./app.py:/app.py
      - voice_restore_data:/data
    networks:
      - voice_restore_net
    environment:
      - FLASK_DATA_PATH=/data/WebSocket
      - FLASK_FILE_PERIOD=15000
      - FLASK_FILE_DUPLICATE=0
    ports:
      - 8301:8000

volumes:
  voice_restore_data:
    external: true

networks:
  voice_restore_net:
    external: true 